export let LIST_COLUMNS = [
    {
        key: 'ID',
        name: 'ID',
        fieldName: 'ID',
        minWidth: 50,
        maxWidth: 100,
        isResizable: true,
    },
    {
        key: 'Title',
        name: 'Title',
        fieldName: 'Title',
        minWidth: 50,
        maxWidth: 100,
        isResizable: true,
    },
    {
        key: 'Email',
        name: 'Email',
        fieldName: 'Email',
        minWidth: 50,
        maxWidth: 100,
        isResizable: true,
    },
    {
        key: 'Batch',
        name: 'Batch',
        fieldName: 'Batch',
        minWidth: 50,
        maxWidth: 100,
        isResizable: true,
    },
    {
        key: 'LevelofKnowledge',
        name: 'LevelofKnowledge',
        fieldName: 'LevelofKnowledge',
        minWidth: 50,
        maxWidth: 100,
        isResizable: true,
    },
]